### PR TITLE
Input number formatting

### PR DESCRIPTION
**Pull request by arvidbjorkstrom**
Changed the input number filter from just filtering out `,` to play nice with different ways of writing numbers in different countries. Also changed the output number format function in the same way. Both using PHP's built in class for this: [NumberFormatter](https://www.php.net/manual/en/class.numberformatter.php)

I'm using the existing locale setting used for currency formatting. Either that should change to a general number formatting setting or maybe another one should be added for other number formatting.

### CODE REVIEW

**Comment by biati-digital** [comment]
Hi, i did not use NumberFormatter as it's not always available. I did try it with the PHP versions included by default in macOS and also with a brew version (don't remember exactly what version was) and received an error "Class 'NumberFormatter' not found PHP" that's why i had to use that workaround.

**Comment by arvidbjorkstrom** [comment]
Ah, that's too bad. Worked on my machine, with a home-brew version of PHP 7. I'll see if I have some other ideas of good solutions.

**Comment by arvidbjorkstrom** [comment]
A combination of [number_format](https://www.php.net/number_format) and [localeconv](https://www.php.net/manual/en/function.localeconv.php) should work and by the looks of it is more readily available.

**Comment by biati-digital** [comment]
Yeah, it would be great to use `NumberFormatter` but will not work for a lot of users.

i also tried `number_format`, it was included in older versions of the workflow, the problem was that some users complained because `number_format` will round up, they showed examples of other workflows and they were right, removing `number_format` "solved" that problem but the current implementation is far from perfect, the last time i saw that part of the code i wanted to rewrite it but i was not even sure why i wrote that function that way and i had no other ideas so i did not change anything.

**Comment by arvidbjorkstrom** [comment]
I updated the pull request and reworked the code from using NumberFormatter to using localeconv to get the locale specific delimeters and number_format to display the number.

I'm doing the rounding/decimal cut before using `number_format` to present the value, but there might of course be other issues.

One thing that I've bee thinking of while looking around in the code is the decimal handling. Maybe the number of decimals and if the numbers should be rounded or cut should be a setting? Or maybe just follow the input value? If the user inputs a value with 3 decimals, show output with three decimals?
Do you have any thoughts on that?

**Comment by biati-digital** [comment]
There's been some requests about the ability to define decimals depending on the tool, for example, being able to define 2 decimals for currency and for units to be able to have more, etc. So i think it should be a setting. I was working on an update to include those options.

CleanShot 2023-02-06 at 19 49 59

But still, i'm not sure about the rounding, if i remember correctly, number_format will always round up so it might work in some cases, not sure if that should be a setting, i think the rounding should be added by default in some tools, for example, `currency, crypto, percentage, etc`. Some other tools like `units, pxemrem`, should not round as results can be different from what the user is expecting. What do you think?

**Comment by arvidbjorkstrom** [comment]
Maybe have a default behavior with two decimals, but intelligently follow the number of decimals of the input value. And have the option-copy be the full value with all decimals?

By intelligently following I mean something like this:
1. If the output has no non-zero decimals (1.00) and the input had no decimals - show no decimals 
`100 cm m` outputs `1 m`
2. If the output has decimals, and the input had no decimals - default to 2 decimals
`1 m in` outputs `39.37 in`
3. If the output has decimals, and the input had decimals - follow the input number of decimals
`1.234 m in` outputs `48,583 in` and `1.2 m in` outputs `47.2 in`

**Comment by biati-digital** [comment]
I've been doing some tests, you use `localeconv` but in many cases the `thousands_sep` and `decimal_point` are not correct or empty. Seems that the locale must be installed in order to display the data correctly. I think it's easier to simply provide options for the user to specify the decimal separator just like Alfred already does.

CleanShot 2023-03-12 at 20 49 30

**Comment by arvidbjorkstrom** [comment]
Yes, this is probably a more compatible, better solution.

**Pull request closed without merging**
