### PR TITLE
Fixed some bugs

### PR DESCRIPTION
**Pull request by augusl**

### CODE REVIEW

**Comment by biati-digital** [comment]
hi @augusl thank's for the PR, I've a new update that will be released today, it changed a lot, would you mind checking your PR agains the update once released?

I'm not using `??` as I wanted to provide support for previous versions of Mac OS, also is there a reason for changes like this `if (!empty($converted['error'])) {` instead of `if ($converted['error']) {` by default error will be `false` so both versions of the code work the same way... I think.

Lastly strtotime (line 472),  the value it's already a timestamp, well, at least in the new version as different providers returned the value in different formats. This part was modified to always store a timestamp.

**Comment by augusl** [comment]
> hi @augusl thank's for the PR, I've a new update that will be released today, it changed a lot, would you mind checking your PR agains the update once released?
> 
> I'm not using `??` as I wanted to provide support for previous versions of Mac OS, also is there a reason for changes like this `if (!empty($converted['error'])) {` instead of `if ($converted['error']) {` by default error will be `false` so both versions of the code work the same way... I think.
> 
> Lastly strtotime (line 472), the value it's already a timestamp, well, at least in the new version as different providers returned the value in different formats. This part was modified to always store a timestamp.


Okay, thank you. I'll resubmit it

**Comment by augusl** [comment]
> `if (!empty($converted['error'])) {` instead of `if ($converted['error']) {`

”if (!empty($converted['error'])) { instead of if ($converted['error']) { “ The reason for this change is, My php.ini default configuration file “error_reporting = E_ALL”  There will be a Notice error,The result cannot be displayed to alfred

**Comment by biati-digital** [comment]
ahhh i see, the problem is that if there's no errors then the `error` key will not exist in `$converted`, when using only `if ($converted['error']) {` there will be an error notice as `error` is not set, !empty will check that 'error' key is set.

In the latest version the 'error' key will always be returned even if there's no errors (it's value will be `false` if no errors or a string with the error message), so you won't see that Notice.

I'll have to pospone the update for tomorrow as I also have to update the README and the gifts.

**Comment by augusl** [comment]
> ahhh i see, the problem is that if there's no errors then the `error` key will not exist in `$converted`, when using only `if ($converted['error']) {` there will be an error notice as `error` is not set, !empty will check that 'error' key is set.
> 
> In the latest version the 'error' key will always be returned even if there's no errors (it's value will be `false` if no errors or a string with the error message), so you won't see that Notice.
> 
> I'll have to pospone the update for tomorrow as I also have to update the README and the gifts.

OK,good job

**Pull request closed without merging**
